### ISSUE TITLE
Doesn't work in 1.18+

### ISSUE THREAD

**Issue by JubeanHamukea** [juancarloscp52/BedrockIfy#134]
Whenever I use the latest version (1.18) the game keeps crashing upon launch. I don't think it is my mod-pack, as it has not changed for a long time and Bedrockify used to work before 1.18. This is the crash report:
[crash-2022-01-24_14.42.57-client.txt](https://github.com/juancarloscp52/BedrockIfy/files/7922470/crash-2022-01-24_14.42.57-client.txt)

**Comment by juancarloscp52** [comment]
Hi! This is caused by an incompatibility with optifine versions for 1.18.1. But there's a work around:
Temporally disable Optifine and Optifabric. Run minecraft and go to bedrockIfy settings, mixins tab and disable the entry: "client.features.bedrockShading". Now you should be able to enable optifine without the game crashing
