### ISSUE TITLE
Graphic bug 1 17 1 incompatibility with colormatic

### ISSUE THREAD

**Issue by ghost** [juancarloscp52/BedrockIfy#146]
![2022-04-06_10 27 19](https://user-images.githubusercontent.com/80956290/161919656-82bb34e8-d956-4701-bade-fcb4d7570176.png)
![2022-04-06_10 28 03](https://user-images.githubusercontent.com/80956290/161919673-6dd5348a-dbc2-4f05-8c3d-0ba5dc1d3404.png)
When installing the coloramatic mod
And a resource pack for a water color map
Biome noise stops working

**Comment by juancarloscp52** [comment]
Hello! (sry for the big delay)  This issue is caused because colormatic and bedrockIfy are changing the same component in minecraft. This causes the modifications to conflict and choose the modification with highest priority. There is no easy way of making these two water modifications work at the same time and looks like it is prioritizing colormatic over bedrockify, which in my opinion is fine as water noise is not important as water color modifications from colormatic for the user.
