### ISSUE TITLE
[feature request] bedrock cauldrons

### ISSUE THREAD

**Issue by OtherMongrel** [juancarloscp52/BedrockIfy#176]
Cauldrons
Are block entities.
Can hold potions.
Liquid inside can be transparent.
Water in cauldrons can be coloured.
Leather (horse) armour dyeing has to be done through the cauldron rather than a crafting grid.

**Comment by lonefelidae16** [comment]
I’ve been thinking about this issue a bit. There are some cauldron mods out there, but I cannot find one that holds Potions. It’s interesting and fun to understand the Bedrock’s behavior.

So, I finally did it. I think it will be fine since I had so many cauldrons filled with Potions lined up and no FPS drops or crashes on my instance.

But it looks like the cauldron needs to be modified more tightly to make the fluid translucent.

![screen_shot_20230221.png](https://user-images.githubusercontent.com/74746227/220338001-c985bcc3-44a4-47bf-a26a-1701a6e53c8d.png)

I’ll post a link to my branch for now since there is a conflict. I’ll create a new PR when ready!

~[lonefelidae16:feat/cauldron-behavior](https://github.com/lonefelidae16/BedrockIfy/tree/feat/cauldron-behavior)~
Edit: successfully merged into upstream.

**Comment by juancarloscp52** [comment]
This feature is looking great! :100: 

>  But it looks like the cauldron needs to be modified more tightly to make the fluid translucent.

If not possible, it is not a deal-breaker as java cauldron are also not translucent and I suspect it might be a difficult feat.
