### ISSUE TITLE
Version 1.5 is incompatible with Carpet Extra

### ISSUE THREAD

**Issue by SplendidAlakey** [juancarloscp52/BedrockIfy#188]
**MC** 1.19.2
**FAPI** 0.62.0
**Bedrockify** 1.5
**[Carpet Extra](https://www.curseforge.com/minecraft/mc-mods/carpet-extra)** 1.4.83

The game simply crashes on startup: https://gist.github.com/Footage2-Amply-Pounce/ba22a42443df15ec9cdbe0c1303bfff6

**Comment by juancarloscp52** [comment]
Hi! this is caused because bedrockIfy and carpet extra are implementing the same feature (bonemeable sugar cane). For now, you can go to the bedrockify mixin settings file in the config folder, search for `common.features.fertilizableBlocks` and set it to `false`. Alternatively you can load the mod with carpet extra temporally disabled an in the bedrockIfy settings menu, in the mixin category set the previously said value to false. 

In the next update I'll add this so users does not have to do it manually.

**Comment by SplendidAlakey** [comment]
Would that also disable other bonemealable blocks? If so, I'd rather manually remove that mixin from Carpet Extra.

**Comment by juancarloscp52** [comment]
this manual setting will remove other new bonemeable blocks. The fix i'm working on will only disable sugar cane and users will need to enable carpet setting /carpet betterBonemeal true.

**Comment by SplendidAlakey** [comment]
Ah, sounds perfect then, thanks!

**Comment by juancarloscp52** [comment]
fix pushed, I'll hold the release for some days in case any other issue appears. Thanks for posting this issue!
