### ISSUE TITLE
Reach-Around Block Placement breaking with Mud block

### ISSUE THREAD

**Issue by Goober19** [juancarloscp52/BedrockIfy#202]
I love the Reach Around Block Placement method but im noticing that if I try to use it with the mud block, it tries to place it one block down, then it disappears immediately. Heres the clip:

https://streamable.com/x1j2bu

**Comment by Goober19** [comment]
also doesnt let you place other blocks (that do work) on the edge of mud blocks

**Comment by juancarloscp52** [comment]
Should be fixed now. When placing other blocks (blocks that are full size) around a mud block (or any other block that is not full size)  you have to be positioned a bit further from the edge of the block so that your player hitbox does not conflict with the new full size block. Thanks for opening this issue!
