### ISSUE TITLE
Mod conflict with Haema

### ISSUE THREAD

**Issue by RDKRACZ** [juancarloscp52/BedrockIfy#27]
MC crashes when loading BedrockIfy and Haema mod.

Reported to williambl too - https://github.com/williambl/haema/issues/19

crash report - https://hatebin.com/tbgimqyrle
latest.log - https://hatebin.com/ithepnggws

**Comment by juancarloscp52** [comment]
Hi! Thanks for opening this issue. This problem is caused because Haema and BedrockIfy both modify the same part of code inside the minecraft source code. There isn't an easy fix to this other than disabling this specific portion of code (mixin) inside Bedrockify (this would disable the screen safe area feature). As of the current version disabling mixins is not supported on BedrockIfy but I plan on doing a refactor to the code so mixins can be disabled. Sadly, I can't promise a release date of this future version as it would take some time and I'm currently very time limited.

**Comment by juancarloscp52** [comment]
Hi again!! BedrockIfy has been updated and now supports disabling mixins with version 0.2.0+. To run BedrockIfy with Haema mod, you have to disable the "client.features.screenSafeArea" mixin inside the Mixins tab in the BedrockIfy Settings menu. You might have to disable Haema in order to enter the bedrockify settings and then reenable it after the specified mixin has being disabled.

**Comment by K0-RR** [comment]
Ok but how will disabling this mixin affect bedrockify?

**Comment by juancarloscp52** [comment]
You will not be able to use the Screen Safe Area (screen border) feature. The rest of bedrockify features should work normally.
