### ISSUE TITLE
Hand Swaying is misaligned between main and off hands

### ISSUE THREAD

**Issue by mttic** [juancarloscp52/BedrockIfy#332]
When hand swaying is enabled, both hands will bob, but out of sync. This feels like a bug, since the swaying is meant to reflect the player's idle animation in third person view, which has both arms swaying in sync with one another.

Perhaps unrelated, but the swaying also stops when you have an empty hand

**Comment by kikawaa** [comment]
An empty hand is not supposed to sway, also if holding an item in both hands at the same time both of them start bobbing twice as fast.

**Comment by mttic** [comment]
An empty hand doesn't sway on Bedrock Edition, but neither does the off-hand. This is easiest seen when a shield is held, and it feels more like an oversight than an intended feature.

**Comment by lonefelidae16** [comment]
Can confirm. In Bedrock Edition, offhand does not sway. And the variety of items we can hold is far less than in Java.

> When hand swaying is enabled, both hands will bob, but out of sync. This feels like a bug, since the swaying is meant to reflect the player's idle animation in third person view, which has both arms swaying in sync with one another.

Please look closely at your arms. The sway is synced, but the position is slightly different. I think author intentionally made it async, it’s a well thought out implementation, isn’t it?

> also if holding an item in both hands at the same time both of them start bobbing twice as fast.

I’m wondering about this. I know this is not the purpose of this issue, but I’ll try to make a pull to fix this.

**Comment by mttic** [comment]
Woah, you're right! I've played this game for so long and never realized that the position is slightly different. This does seem like a well thought implementation by the author, so not a bug, but I do think there should at least be a config option to synchronize the positions of the items since the off-hand and main hand are synchronized in animations such as view bobbing and using items. This is just a feature request though.

**Comment by juancarloscp52** [comment]
As commented by lonefelidae the implementation is intended. What was not intended was the animation being faster when holding two items. Thanks for noticing and since now it is fixed (thanks @lonefelidae16 ) i'll close this issue.


> I do think there should at least be a config option to synchronize the positions of the items since the off-hand and main hand are synchronized in animations such as view bobbing and using items. This is just a feature request though.

@Matynns Do you mind opening a new issue with this feature request for future elaboration? Thank you.

**Comment by kikawaa** [comment]
> An empty hand doesn't sway on Bedrock Edition, but neither does the off-hand. This is easiest seen when a shield is held, and it feels more like an oversight than an intended feature.

it is intended in bedrock, im pretty sure that offhand doesn't bob on bedrock edition because it will be hard to sync it with mainhand, and adding inconsistent bobbing for the offhand would be worse, and not adding breathing bob at all would be even worse, so their decision to not add breathing bob to the offhand on bedrock is understandable
