### ISSUE TITLE
About the 1.21 update

### ISSUE THREAD

**Issue by vico93** [juancarloscp52/BedrockIfy#350]
I saw that you've commited an initial update to 1.21 and commented "Lacks testing". Just for you to know that, if needed, i can help you with testing.

**Comment by 9ineven** [comment]
Same here.

**Comment by TsengFayt** [comment]
Agreed, Bedrockify is among the first mods I always add to my worlds. I am happy to test if that is possible!

**Comment by GrassyTrams** [comment]
Me too!

**Comment by seriousfreezing** [comment]
If someone knows how to program or something, I recommend that they fork or try to release the code adapted for 1.21 as a pull request here.

**Comment by juancarloscp52** [comment]
Hello! Thank you all for your comments. Here's an alpha version in case you wanna try it. There are still some issues i'm working on fixing and some things that i have not tested yet.
**Known Issues:**
- Config screen shows a black background.
- Paper Doll produces vertex explosions on certain situations (Iris/soduim related?)

*Please backup your world/server before trying it. This version should be fine but i'm not responsible if anything in your world breaks*

File is a zip due to github file restrictions. Please unzip
[bedrockify-1.9.5-dev-a+mc1.21.zip](https://github.com/user-attachments/files/15936733/bedrockify-1.9.5-dev-a%2Bmc1.21.zip)


PS: I hope to have the mod ready for next week/weekend. Thank you for your patience!

**Comment by vico93** [comment]
Thanks a lot @juancarloscp52! Will test and report any issues

**Comment by vico93** [comment]
Apparently there is a weird text scrolling bug in the mod options screen if we access it via either Mod Menu or the button on the Options screen. Weirdly, this only happens out of the game, when accessing it while playing on a save it didn't happen (and the background is the world itself, not black like accessing out of game does.

https://github.com/juancarloscp52/BedrockIfy/assets/3485505/53f1729c-69bd-46d7-871e-0da69fb54d71

**Comment by juancarloscp52** [comment]
Yep definitely related to the black background issue. I still have to research but might be related to a dependency i'm using for the config screen. Thanks for the info!

**Comment by lonefelidae16** [comment]
Hi there, I’m also testing. I found and try to fix a few more issues than indicated here.

$\color{green}{\textsf{Fixed and committed}}$:

* SunGlare feature - The vector should be inverted
* SavingOverlay feature - Avoid partially blackout when chest and arrow is rendered on Singleplayer; especially Hotbar
* EatingAnimations feature - Disable when [NotEnoughAnimations](https://www.curseforge.com/minecraft/mc-mods/not-enough-animations) is loaded

$\color{orange}{\textsf{Found}}$:

* ~EatingAnimations feature - Weird arm position; compatibility issue with NotEnoughAnimations~
  - ~<sup>I don’t mind, but I have a feeling there are some who do...</sup>~
* Cauldron feature - Vanilla’s swap armor functionality triggers after dyed a dyeable item
  - <sup>I just copied codes from CauldronBehavior, but it happens from 1.20.5... why?</sup>

----

Committed branch is available:

https://github.com/lonefelidae16/BedrockIfy/tree/port/1.21

Juan, I’m ready to create a pull about fixed issues if you need. Whenever you want.

**Comment by juancarloscp52** [comment]
Hi! I noticed and fixed the sunglare issue too but forgot to commit it. The dev jar that i sent has the issue fixed haha.

Since it seems that you've been able to squash some more bugs, feel free to open a PR with those three things (including the sunglare fix) and i'll finish up testing and fix the rest that i see.

> Cauldron feature - Vanilla’s swap armor functionality triggers after dyed a dyeable item
I just copied codes from CauldronBehavior, but it happens from 1.20.5... why?

Maybe is because in the 1.20.6 port the cauldron behaviour ActionResult was changed from PASS to FAIL?
![imagen](https://github.com/juancarloscp52/BedrockIfy/assets/11300094/97997af2-92f7-4658-8cb8-c49d4a69c59b)


As always, thank you for everyting!

**Comment by lonefelidae16** [comment]
> Hi! I noticed and fixed the sunglare issue too but forgot to commit it. The dev jar that i sent has the issue fixed haha.

Ohh, yep, I’m just using this repo’s build. Thanks for your reply, I see that’s already fixed, I hadn’t checked.
Okay, I’m going to create a pull for the 1.21 branch now.

> > Cauldron feature - Vanilla’s swap armor functionality triggers after dyed a dyeable item
> > I just copied codes from CauldronBehavior, but it happens from 1.20.5... why?
> 
> Maybe is because in the 1.20.6 port the cauldron behaviour ActionResult was changed from PASS to FAIL?

Original CauldronBehavior code returns `ItemActionResult.PASS_TO_DEFAULT_BLOCK_INTERACTION`, so I’ve changed to that and tested, but it won’t fix... it happens on Multiplayer, doesn’t happen on Singleplayer.
So, I also tried to change forcibly returns `ItemActionResult.SUCCESS` instead of `ItemActionResult#success(World.isClient)`, but it won’t fix too...
`CauldronBehavior#CLEAN_DYEABLE_ITEM` will work propery, so I’m thinking about we need to do stuff in ColoredWaterCauldronBlock.

I’ll give it some more thought, but I’m not sure I can come up with anything right now. I’ll make a pull when I figure it out again.

**Comment by DardS8Br** [comment]
The hotbar loses opacity randomly. I'm not sure if it's intentional, but it is very annoying. I've noticed that it happens while flying with an elytra and while falling, but I'm not fully sure if that's what causes it

**Comment by jokeruarwentto** [comment]
Hello,

- **AppleSkin and Screen Safe Area Compatibility**:  
  I recommend to remove the code related to AppleSkin and Screen Safe Area compatibility to ensure proper functionality.

- **Hotbar Opacity**:  
  The default opacity should not be set to 0.6f, the hotbar isn't transparent in Bedrock from my experience.

- **Days Played Overlay**:  
  This new overlay feature, introduced in Bedrock Edition 1.21, would be a great addition to this mod.

I have forked the repository and created a [1.21-fixes](https://github.com/jokeruarwentto/BedrockIfy/tree/1.21-fixes) branch, which includes the fixes and the new Days Played overlay feature, for the ``Days Played`` feature, I haven't tested it in multiplayer, but I guess it'll not work properly. 

There's no pull request since I've done it for my personal usage, feel free to use what I've done for your needs.
