### ISSUE TITLE
Bedrockify Crashes on Loading 

### ISSUE THREAD

**Issue by BuilderDan** [juancarloscp52/BedrockIfy#85]
Bedrockify crashes on Fabric 0.11.6 on startup.
https://pastebin.com/U7nNDBy4

**Comment by juancarloscp52** [comment]
This is caused by an incompatibility with the last version of Nyf's Quivers. Try disabling this mod. If you want to continue using Nyf's Quivers, temporally disable this mod so bedrockIfy can lunch and disable the "client.features.screenSafeArea" mixin under bedrockIfy's mixin settings. Once this mixin is disabled, you can re-enable the other mod and the game should lunch without problem.

**Comment by BuilderDan** [comment]
Thank you for the detailed response, I will give it a go!

**Comment by Jaozim-123** [comment]
So...I disabled the bedrockify settings button, how can I disable this?
I alredy solved the problem, but for those who have the same problem that I had go to C:\Users\USER\AppData\Roaming\.minecraft\config\bedrockify and set bedrockify settings button to true
